### ISSUE TITLE
Очистка полей дополнительной аналитики в расходах

### ISSUE THREAD

**Issue by FedorovB** [shcherbakov-vadim/1c-money-custom-issues#1]
Добрый день. При загрузке чеков из json в форме расхода очищаются поля дополнительной аналитики, записанные ранее по умолчанию для расходов. То есть они просто исчезают из формы расхода в тех операциях, которые были загружены из чека. Приходится кнопку с аналитикой нажимать и выстраивать их заново.

**Comment by shcherbakov-vadim** [comment]
Необходимо описать последовательность шагов которая приводит к проблеме и крайне желательно добавить скриншоты. По вашему описанию не понятно на каком этапе возникает проблема.

**Comment by FedorovB** [comment]
Добрый день. К примеру, при создании расхода по кнопке "Расход" (без загрузки чека) у меня открывается форма расходас ранее настроенной мной аналитикой:
![Расход](https://github.com/user-attachments/assets/14bbb0f3-0c73-490c-a7a3-fb12c20c8228)
Но если я загружаю чек по кнопке "Загрузить чеки", то все ранее настроенные мной поля аналитики в таком расходе у меня очищаются и мне приходится в каждом загруженном по чеку расходе выстраивать их заново:
![Расход из чека](https://github.com/user-attachments/assets/b8e11531-0fc4-4301-a2d3-78b248bb0bea)
Кнопка "Записать по-умолчанию" в данной ситуации не помогает:
![Записать](https://github.com/user-attachments/assets/0eec7484-a750-4e7e-a563-d9e4146ab38a)

**Comment by FedorovB** [comment]
Вадим, а еще я хотел бы добавить пожелание, чтобы значение из поля "Магазин" во вкладке "Данные чека" при загрузке расхода из чека автоматически переносилось в поле предустановленной аналитики "Магазин, продавец" (в случае, если эта аналитика используется, разумеется).
![Снимок экрана 2024-08-17 114401](https://github.com/user-attachments/assets/b54cbace-66c2-4aca-9039-f5b7203a11f4)

**Comment by shcherbakov-vadim** [comment]
> Вадим, а еще я хотел бы добавить пожелание, чтобы значение из поля "Магазин" во вкладке "Данные чека" при загрузке расхода из чека автоматически переносилось в поле предустановленной аналитики "Магазин, продавец" (в случае, если эта аналитика используется, разумеется). ![Снимок экрана 2024-08-17 114401](https://private-user-images.githubusercontent.com/173467504/358834836-b54cbace-66c2-4aca-9039-f5b7203a11f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODU2NDgsIm5iZiI6MTcyMzg4NTM0OCwicGF0aCI6Ii8xNzM0Njc1MDQvMzU4ODM0ODM2LWI1NGNiYWNlLTY2YzItNGFjYS05MDM5LWY1YjcyMDNhMTFmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwOTAyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOThhOGM1MDlhZDY0NDg2OWJkODI5NDExM2YwNTg0Mjk5NGNjOGIyM2NiMmFmZDY1OWY5MmY4NDc3MmFkNGVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V3rrUKgKCnyPfjSDkKi_wWXcTIFGqz2zOcg92R5dBqM)

Это уже реализовано в версии https://chtch.ru/ru/1sdengi/#2.0.44.28.37
По каждой новой проблеме или предложению необходимо заводить новый Issue, это не чат. Вопросы можно задать в telegram

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.38
