### ISSUE TITLE
Документ Расход. Отключение свертки статей расходов

### ISSUE THREAD

**Issue by KonstantinSolo** [shcherbakov-vadim/1c-money-custom-issues#11]
Документ "Расход".
При загрузке чека, после сопоставления позиций из чека статьям расходов и нажатия на вкладке "Расходы" кнопки [Заполнить по данным чека], содержимое вкладки "Данные чека" сворачивается по статьям расхода и переносится на вкладку "Расходы".
Это не всегда удобно, например, у меня используется аналитика "Члены семьи", и разные строки из чека списываются на разных членов семьи. Аналогично и с аналитикой "Проекты".
Хотелось бы отключить свертку строк чека, или иметь возможность отключения (кому-то, возможно, эта свертка и нужна, если не используется активно аналитика).

**Comment by shcherbakov-vadim** [comment]
Вы пробовали для этих целей использовать кнопку "Привязать расход"? Вы можете выделить несколько строк чека и назначить для них отдельную статью расхода и аналитики.
Можно расширить эту функциональность, чтобы система учитывала статью расхода указанную в строке данных чека и формировала необходимое количество строк.
Тогда может использоваться следующий сценарий:
1. Выделили строки данных чека
2. Нажали на кнопку "Привязать расход"
3. Заполнили в сформированных строках необходимые аналитики

**Comment by KonstantinSolo** [comment]
Т.е. это получается такой алгоритм:
прописал соответствия на второй вкладке, если они не были прописаны
на первой вкладке нажал кнопку "Заполнить по данным чека"
встаю на первую строку  (из тех, что не надо сворачивать) - привязываю ее, меня перекидывает на первую вкладку, указываю статью расхода, заполняю аналитику.
Возвращаюсь на вторую вкладку.
Встаю на вторую строку, привязываю, итд.
так?

Что сразу не понравилось (оговорюсь, это мое личное мнение, не претендующее на истину):
- кол-во и цена на первой вкладке не совпадают с данными из чека (после выбора статьи расхода колво стало 1, цена=сумме). 
- даже если привязываю одну строку - подробности не заполняются (ну это ладно, они у вас вообще никогда не заполняются) и  на первой вкладке статья расхода не заполняется автоматом, хотя на второй вкладке она была указана.
- при записи в черновик или при проведении документа - на первой вкладке остались правильно заполненными только статьи расхода в строках, которые я привязал на второй вкладке. в остальных строках статья расхода заменилась на "_Загрузка чеков" (которая по умолчанию при загрузке чека прописана).

**Comment by shcherbakov-vadim** [comment]
1. Нет, предполагается, что на первой закладке вы будете прописывать только аналитики, а работать вы будете с закладкой "Данные чека". 
То есть на входе мы имеем полностью заполненные данные на закладке "Данные чека". Теперь вы хотите выделить часть из этих расходов на отдельные аналитики. Для этого вы выделяете на закладке "Данные чека" строки и нажимаете на кнопку "Привязать расход...". Выделенные строки группируются по статьям расхода и переносятся на закладку "Расходы". Там вы можете заполнить аналитики и перейти к выделению новой группы строк
2. Для количественных статей количество будет переносится с закладки "Данные чека"
3. Я описывал планируемое поведения. Сейчас при привязке расхода статья расхода на закладке "Данные чека" не учитывается.
4. Если строки на закладке "Расход" не зафиксированы, они будут обновляться по данным закладки "Данные чека". И раз там не заполнены статьи - будет заполнена статья "Загрузка чеков"

Я описал возможный сценарий, когда необходима возможность выдялать часть расходов на отдельную аналитику. Если же у вас стоит задача переносить Данные чека 1-в-1 в Расходы, то нужно делать отдельную кнопку "Заполнить по данным чека без группировки" и тогда у всех строк будет установлен признак "Фикс.", а наименование чека будет заполнено в поле "Подробности"

**Comment by KonstantinSolo** [comment]
Да, в идеале - переносить один в один, в т.ч. колонку "Подробности", кол-во, цену, сумму...

Вопрос - как мне сейчас поступать? Я выделил одну строку, привязал расход. Выделил третью, тоже привязал расход на новую строку (я не хочу, чтобы 1 и 3 строки сгруппировались, поэтому отдельно привязываю). В остальных, допустим, меня устраивает, что они могут свернуться. Я нажимаю "Заполнить по данным чека", в первой вкладке остальное переносится правильно, в соответствии с тем, как я настроил на второй вкладке.
заполняю аналитики (переношу некоторые в шапку (у них одно и то же значение), другие оставляю в табличной части, и тоже заполняю).
Нажимаю "Учесть", документ записывается, проводится, закрывается.
Я открываю, и у меня непонятная ерунда происходит: часть строк остались, в т.ч. те, к которым привязаны были строки из второй вкладки, а в остальных опять стоит статья расхода "_Загрузка чека", которая в настройках прописана по умолчанию. Аналитики тоже у этих строк пустые, вообще, есть только сумма...
если надо - могу попробовать записать видео.
Возможно, имеет смысл попробовать заново загрузить документ (я его столько раз правил, что ХЗ что там внутри уже), могу для начала это сделать - скажите только как? Достаточно будет пометить его на удаление и удалить, чтобы он заново загрузился из почты, или надо сделать что-то еще?

PS: "И раз там не заполнены статьи - будет заполнена статья "Загрузка чеков"" / в том-то и дело, что я сначала прописал все статьи расходов всем строкам на второй вкладке, а только потом стал пытаться проделать разное - разбивать строки, привязать расход..

**Comment by shcherbakov-vadim** [comment]
Вы можете скриншоты описать последовательность действий со скриншотами, чтобы было понятно что именно у вас не получается.
Вы всегда можете полностью очистить строка на закладке Расходы и они автоматически заполнятся по данным закладки Данные чека.

**Comment by KonstantinSolo** [comment]
![2024-11-17 19_28_10-Расход от 15 11 2024 (10_35)_ 4 561,67 руб  из  _Загрузка чеков  _](https://github.com/user-attachments/assets/7e74290f-1bc9-47e7-b0e3-025e2356c818)
![2024-11-17 19_28_40-Greenshot](https://github.com/user-attachments/assets/7fa28d0b-8b75-4f4a-bcf6-e1546818ce8a)
![2024-11-17 19_29_24-Greenshot](https://github.com/user-attachments/assets/96e659e5-bf7d-455b-ae2c-5df926b39505)
![2024-11-17 19_29_36-Greenshot](https://github.com/user-attachments/assets/63b3ef75-b69a-45f3-bbb4-071a3a7a4ecb)
![2024-11-17 19_30_06-Greenshot](https://github.com/user-attachments/assets/b28c1ae0-de01-404d-9d12-0f9600762274)
![2024-11-17 19_30_45-Greenshot](https://github.com/user-attachments/assets/50707e19-4e37-4708-8c47-d18772a1ee4f)
![2024-11-17 19_31_21-Greenshot](https://github.com/user-attachments/assets/449b441e-66b6-43b3-b265-d18703fc854a)
![2024-11-17 19_31_31-Greenshot](https://github.com/user-attachments/assets/827be696-11c3-452c-bd90-142180e136ff)
![2024-11-17 19_32_00-Greenshot](https://github.com/user-attachments/assets/ccbb0886-9136-45d5-9da6-251d05197028)
![2024-11-17 19_32_20-Greenshot](https://github.com/user-attachments/assets/afe93950-3022-4e32-b176-48246fdedacc)
![2024-11-17 19_33_56-Greenshot](https://github.com/user-attachments/assets/138dda1e-610e-4dc3-93b0-34ae4aa920c7)
![2024-11-17 19_34_48-Greenshot](https://github.com/user-attachments/assets/422c5cfb-6f24-445f-90bd-6e8d1820da36)
![2024-11-17 19_35_26-Greenshot](https://github.com/user-attachments/assets/42d0c159-5383-45fa-a3f4-584cddde45fe)

**Comment by shcherbakov-vadim** [comment]
1. При заполнении аналитики на закладке "Расходы" у строки должен был автоматически установиться флаг "Фикс.", чтобы система не пыталась эти строки перезаполнить по данным закладки "Данные чека". Вы снимали этот флаг? Если да, то зачем?
2. Если у статьи, указанной на закладке "Данные чека" есть аналитики без значений по умолчанию, то при проведении документа они будут заменены на статью по умолчанию. Ожидается что пользователь нажмет на кнопку "Заполнить по данным чека" и при установке аналитик зафиксирует эти строки (см.п.1)

**Comment by KonstantinSolo** [comment]
1. "Вы снимали этот флаг?"
при первых попытках редактирования - да, пробовал и снимать. В этот раз, когда делал скриншоты - не делал. Зачем? - подумал, что при включении флага не сохранится соответствие статьям расхода, прописанное на второй вкладке. 

2. Это я уже понял))) Сейчас загрузился новый чек, в нем в шапку аналитики не перекидывал, заполнял все в табличной части. Сделал одну привязку к расходу. При этом все сохранилось нормально. После проведения документ открыл - все ок. Перенес пару аналитик в шапку и провел еще раз - все ок. Посмотрел движения документа - все ок.
Придет еще чек - попробую до сохранения документа перенести аналитики в шапку. Но, думаю, все ок будет.

Получается, первый док глючит из-за неправильной работы пользователя, а потом внутри какие-то настройки сохранились и теперь он никак нормально не может работать... попробую еще поиграться с ним...

Ну и остались мои личные хотелки, которые ХЗ нужны ли еще кому-то, с переносом строк из второй вкладки в первую без свертки и с переносом колонки "Наименование" aka "Подробности". Свертка лично мне не нужна еще потому, что я 
стараюсь править кол-во, чтобы цена у меня была сохранена везде на единицу продукции, например, "молоко 1 бутылка (0,93л,)" - я правлю колво на 0,93, чтобы цена была за 1литр, чтобы можно было сравнить цену в разных магазинах и разных бутылках (где-то литр, где-то 0,9..)..

**Comment by KonstantinSolo** [comment]
"первый док глючит из-за неправильной работы пользователя, а потом внутри какие-то настройки сохранились и теперь он никак нормально не может работать... попробую еще поиграться с ним..."
Да, удалил документ, выгрузил чек заново на почту, он загрузился, я очистил первую вкладку, привязал на второй вкладе 3 строки, остальное заполнил автоматически, прописал аналитики на первой вкладке, провел - все ок. Табличная часть не сбросилась, движения документа нормальные.

**Comment by KonstantinSolo** [comment]
Очередной чек. И, думаю, это глюк..

На этот раз после сопоставления статей расхода на второй вкладке и перехода на первую (и заполнения по данным чека), перенес одну аналитику в шапку, чтобы не заполнять ее в каждой строке.
И провел документ. 
После открытия опять вижу неверную картинку, одна из строк запомнилась (видимо, потому что там все аналитики взяты по умолчанию), остальные - "Загрузка чека", заполнена только сумма, ни кол-ва, ни цены, ни аналитик.
Замечу, что после переноса аналитики в шапку, она осталась заполненной нужным мне значением, видимо, поэтому ни в одной строке флажок "фикс." (на первой вкладке) не был включен автоматически (я его тоже не трогал).

На второй раз после заполнения по данным чека я перенес аналитику в шапку, перевыбрал (оставив то же самое значение), и вернул аналитику в табл.часть. При этом аналитика была везде заполнена, но флажок "фикс." все равно не был нигде включен. 
Ну и понятное дело, после проведения табличная часть на первой вкладке опять сбросилась, 1 строка заполнена и несколько строк "загрузка чека". 

В третий раз опять заполнил по данным чека, перенес аналитику в шапку (она была заполнена), не меняя ее - сразу перенес аналитику в табл. часть (она стала заполнена во всех строках), и поставил вручную флажок "фикс" на первой вкладке на всех строках.
После проведения все осталось как было.

**Comment by shcherbakov-vadim** [comment]
По каждой проблеме нужно описание порядка действий со скриншотами

**Comment by KonstantinSolo** [comment]
"Вы всегда можете полностью очистить строка на закладке Расходы и они автоматически заполнятся по данным закладки Данные чека."
конечно в каждую попытку я удалял сначала все строки на первой вкладке. Это не помогает, если я перенесу аналитику в шапку и оставлю там или перенесу обратно заполненную, все равно галки "факт" не включаются, и при проведении сбрасываются. 
Скрины постараюсь попозже скинуть

**Comment by KonstantinSolo** [comment]
Вот обещанные скрины.
![2024-11-21 12_38_29-Конфигуратор - _c__1c_db_test2a__ -  Внешний отчет(обработка) - H__DATA_HAWK_SUP](https://github.com/user-attachments/assets/b79a597d-393e-47e7-8818-3b17d2da853e)
![2024-11-21 12_40_27-Конфигуратор - _c__1c_db_test2a__ -  Внешний отчет(обработка) - H__DATA_HAWK_SUP](https://github.com/user-attachments/assets/4a2765a8-526a-4368-889c-946df6000cc4)
![2024-11-21 12_40_55-Конфигуратор - _c__1c_db_test2a__ -  Внешний отчет(обработка) - H__DATA_HAWK_SUP](https://github.com/user-attachments/assets/a5277abe-b110-4908-a5a4-3c849d2e5b6b)
![2024-11-21 12_41_50-Конфигуратор - _c__1c_db_test2a__ -  Внешний отчет(обработка) - H__DATA_HAWK_SUP](https://github.com/user-attachments/assets/bf10fb0e-2cbf-41ba-90af-e1da7718676a)
![2024-11-21 12_43_20-Расход от 20 11 2024 (16_31)_ 3 551,54 руб  из  _Загрузка чеков  _](https://github.com/user-attachments/assets/fe2836cd-6de8-403d-80a8-2dd09f2c452e)
![2024-11-21 12_43_52-](https://github.com/user-attachments/assets/8c3144b9-3ed6-447a-a9ae-4c12eb0bb583)
![2024-11-21 12_44_12-Конфигуратор - _c__1c_db_test2a__ -  Внешний отчет(обработка) - H__DATA_HAWK_SUP](https://github.com/user-attachments/assets/ddcca926-50d5-46da-b49e-404d9b78308b)
![2024-11-21 12_47_39-Конфигуратор - _c__1c_db_test2a__ -  Внешний отчет(обработка) - H__DATA_HAWK_SUP](https://github.com/user-attachments/assets/992c8a11-eda8-409f-9905-5e5080e06f0a)
![2024-11-21 12_48_58-Конфигуратор - _c__1c_db_test2a__ -  Внешний отчет(обработка) - H__DATA_HAWK_SUP](https://github.com/user-attachments/assets/e02a3527-4400-4dd9-9052-2e7201288d83)
![2024-11-21 12_50_29-Конфигуратор - _c__1c_db_test2a__ -  Внешний отчет(обработка) - H__DATA_HAWK_SUP](https://github.com/user-attachments/assets/6a1f0981-abd6-4508-90c5-207fc8f8a786)
![2024-11-21 12_51_31-](https://github.com/user-attachments/assets/6548361f-9e7e-4683-9fdf-42eef623253d)

**Comment by shcherbakov-vadim** [comment]
В следующий раз нумеруйте пожалуйста скриншоты

1.  Сопоставления наименований чека хранятся в разрезе каждого магазина, поэтому при смене магазина система спрашивает нужно ли перенести сопоставление наименований текущего чека в новый магазин. Вы вероятнее всего ответили нет, поэтому сопоставления очистились, а при проведения незафиксированные строки на закладке "Расход" заполнились по закладке "Данные чека".
2. Про действия с документами написано в https://chtch.ru/ru/1sdengi#2.0.40.12.4 и https://chtch.ru/ru/1sdengi#2.0.44.28.39.
Система нашла чек с таким же ИНН, чтобы поменять в нем магазин. Чтобы перенести сопоставления этого чека в новый магазин нужно было установить флаг "Сохранить существующие соответствия для нового магазина". Вы оставили флаг сброшенным в указанном чеке сопоставления очистились.

Про перенос аналитик просьба сделать отдельный пример вручную с одной аналитикой и парой строк, чтобы я мог его воспроизвести

Учитывая, что вы на каждый вид товара сделали отдельную статью, можно ли считать, что отключение свертки вам больше не нужно?

**Comment by KonstantinSolo** [comment]
"В следующий раз нумеруйте пожалуйста скриншоты". Вы имеете в виду - добавить прямо на скриншот его номер? т.к. в имени файла указана дата время скрина, т.е., по идее, они должны быть по порядку расположены...

1. нет, если я не сразу указал магазин, а после сопоставления чека или его части, я всегда соглашался с переносом сопоставлений. Да и если бы не согласился, разве после этого во второй вкладке не появились бы несопоставленные строки? А у меня таких не было

2. правильно ли я понял - если я согласился, то он найдет все документы с инн этого магазина, и, если там не поставлены галки на "фикс", заменит статьи расхода на те, что я заново сопоставил?

3. про перенос аналитик - ок. Позже сделаю.

4. Нет, отключение свертки нужно по-прежнему, т.к. несколько строк из чека могут быть сопоставлены с одной статьей расхода, т.е. в первой вкладке они будут свернуты, а при этом у каждой строки чека могут быть проставлены свои аналитики. Как пример - купил несколько вкусняшек, но одна строка чека - мне, другая - жене, третья и четвертая - детям. Т.е. аналитика "Члены семьи" будет у всех строк чека разная.

**Comment by KonstantinSolo** [comment]
3. попробовал вручную создать расход - все ок, видимо, тут проблема именно когда загружаешь чек. Подожду, когда придет небольшой чек

**Comment by KonstantinSolo** [comment]
Выкладываю пример. 3 строки в чеке, свернулись в одну статью расхода.
![01](https://github.com/user-attachments/assets/9cca61d2-6c44-45b3-b198-47d8808e28fc)
![02](https://github.com/user-attachments/assets/9a4dc40c-5312-4697-b6ab-87d1b4c17f8e)
![03](https://github.com/user-attachments/assets/225a517c-034e-41bb-accc-3189345c28c8)
![04](https://github.com/user-attachments/assets/46a0a6b8-93a2-4474-a72f-1d562cff0f5e)
![05](https://github.com/user-attachments/assets/f4883d58-6ceb-4358-b3ed-78e92463782c)
![06](https://github.com/user-attachments/assets/fd6bfa33-ad3d-4dd9-a8df-488e639ad520)
![07](https://github.com/user-attachments/assets/f6ff9c6d-8733-4b09-8e67-2fd13fe2df7e)
![08](https://github.com/user-attachments/assets/4cbd26f6-4004-4cb9-b12c-3e8e5a71970f)
![09](https://github.com/user-attachments/assets/401e4cc4-2a0c-48c1-8ce5-7d6492faf779)

**Comment by shcherbakov-vadim** [comment]
> Выкладываю пример. 3 строки в чеке, свернулись в одну статью расхода.

Я ожидал, что вы сделаете отдельный issue на проблему с аналитиками, т.к. она не имеет отношения к теме текущей проблемы
По всей видимости вы для всех аналитик установили признак "Проверять заполнение" и не заполнили значение по умолчанию. Это означает, что при загрузке чека будет заполнено значение статьи по умолчанию (в вашем случае это "_Загрузка чеков") и вы должны будете открыть документ, нажать на кнопку "Заполнить по данным чека" и заполнить эти аналитики вручную. При этом автоматически установится признак "Фикс" и данные по данной строке не будут перезаполняться по данным чека
У вас на скриншоте 7 написано, что вы установили признак "Фикс", хотя он не установлен. Все дальнейшее поведение - ожидаемо

**Comment by shcherbakov-vadim** [comment]
> "В следующий раз нумеруйте пожалуйста скриншоты". Вы имеете в виду - добавить прямо на скриншот его номер? т.к. в имени файла указана дата время скрина, т.е., по идее, они должны быть по порядку расположены...

Нумерация нужна, чтобы на скриншоты можно было ссылаться. Не обязательно писать прямо на скриншоте, можно "номер пункта. описание действия" а ниже скриншот

> 1. нет, если я не сразу указал магазин, а после сопоставления чека или его части, я всегда соглашался с переносом сопоставлений. Да и если бы не согласился, разве после этого во второй вкладке не появились бы несопоставленные строки? А у меня таких не было

В предыдущем ответе я описал причину этого поведения.

> 2. правильно ли я понял - если я согласился, то он найдет все документы с инн этого магазина, и, если там не поставлены галки на "фикс", заменит статьи расхода на те, что я заново сопоставил?

Если поставите флаг "Сохранять существующие соотвествия для нового магазина", то система после замены магазина в чеке сохранит для него все соответствия указанные в документе

> 4. Нет, отключение свертки нужно по-прежнему, т.к. несколько строк из чека могут быть сопоставлены с одной статьей расхода, т.е. в первой вкладке они будут свернуты, а при этом у каждой строки чека могут быть проставлены свои аналитики. Как пример - купил несколько вкусняшек, но одна строка чека - мне, другая - жене, третья и четвертая - детям. Т.е. аналитика "Члены семьи" будет у всех строк чека разная.

Можно тогда добавить на закладку "Данные чека" кнопку для переноса на закладку "Расходы" отдельных строк без привязки. Тогда вы сможете выделить несколько строк (или одну), которые хотите разбить по аналитикам на закладке "Данные чека", после нажатия на кнопку они сгруппированные попадут на закладку "Расходы" и там вы уже сможете разбивать их по аналитикам с автоматической установкой признака "Фикс."

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.41
