### ISSUE TITLE
Невозможно загрузить файл формата Excel в режиме "Загрузить выписку банка"

### ISSUE THREAD

**Issue by Allataus** [shcherbakov-vadim/1c-money-custom-issues#12]
Здравствуйте!

В кастомверсии не получается загрузить файл формата Excel в режиме "Загрузить выписку банка", который загружался без проблем в базовой версии Денег.
При попытке загрузки файла выходит сообщение об ошибке.
![Снимок1](https://github.com/user-attachments/assets/bbe38bdf-a041-42ca-9202-e6bcf1d86483)

Сам файл для проверки загрузки во вложении + архив с ошибкой.
[export.xls](https://github.com/user-attachments/files/17792010/export.xls)
[Ошибка_20241117212253.zip](https://github.com/user-attachments/files/17792022/_20241117212253.zip)

**Comment by shcherbakov-vadim** [comment]
Выложенный вами файл export.xls в формате Excel 5.0/95, который не поддерживается на уровне платформы. Вы можете просто попробовать открыть его через Файл/Открыть и получить ошибку формата
Если сконвертировать его хотя бы в формат Excel 97-2003, то проблема не воспроизводится

**Comment by Allataus** [comment]
[export.xlsx](https://github.com/user-attachments/files/17792208/export.xlsx)
Извиняюсь не тот файл вложил. Вот этот файл в последней версии Excel

**Comment by shcherbakov-vadim** [comment]
Сделайте пожалуйста скриншот списка показателей в правилах чтения табличного документа. Вероятнее всего Ключ показателя был изменен вручную на некорректное значение

**Comment by shcherbakov-vadim** [comment]
Мне удалось воспроизвести проблему. Она связана с настройкой заполнения добавленной аналитики. Будет исправлено в следующей версии конфигурации

**Comment by Allataus** [comment]
Спасибо

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.41

**Comment by Allataus** [comment]
Добрый день! Загрузил последнюю версию custom_1c_money_2_0_44_28_44, но, к сожалению, так и не получается в ней загрузить через раздел загрузки выписки мой файл. Выходит сообщение: Из указанного файла не удалось получить список операций. Проверьте корректность файла и правила его чтения". Допускаю, что где-то в правилах что-то надо поправить, но вот где? 
[export.xlsx](https://github.com/user-attachments/files/17998312/export.xlsx)
![Снимок экрана 2024-12-03 225004](https://github.com/user-attachments/assets/d2cd1872-58c6-47a5-bd31-aeb13565da9a)
![Снимок экрана 2024-12-03 224945](https://github.com/user-attachments/assets/713d6938-8e56-4b93-9b1b-fceee87d0833)
![Снимок экрана 2024-12-03 224917](https://github.com/user-attachments/assets/5970156e-a13a-4c3a-b3fb-727ccab0b81f)
![Снимок экрана 2024-12-03 224854](https://github.com/user-attachments/assets/4c255fc8-9f26-4da6-b906-5586ec166ef9)
![Снимок экрана 2024-12-03 224807](https://github.com/user-attachments/assets/ca0c5ec8-a178-4078-b0c5-86b001a310aa)

**Comment by shcherbakov-vadim** [comment]
Там комментарий есть, что в качестве начала таблицы операции необходимо указывать левый верхний угол списка. У вас сейчас указано начинать с заголовков. Также нужно указывать и расположение остальных показателей, из второй строки
