### ISSUE TITLE
Дата запрета редактирования

### ISSUE THREAD

**Issue by FedorovB** [shcherbakov-vadim/1c-money-custom-issues#13]
Вадим, добрый день. Иногда возникает необходимость установить дату запрета редактирования документов, чтобы случайно не провести какой-то документ (или документы) "очень уж задним числом". У меня пару раз были моменты, когда я, не глядя, проводил какие-то документы задним числом уже в закрытом периоде, а потом искал - что именно я провел неправильно и редактировал там даты. Скажите пожалуйста, не будет ли затруднительным добавить в базу функционал установки даты запрета создания / редактирования документов? Заранее Вам благодарен.

**Comment by KonstantinSolo** [comment]
Желательно также не забыть при этом вариант программного проведения документов. Например, при групповой обработке (это я уже из собственного недавнего опыта, забыл это учесть))) ).

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.45
