### ISSUE TITLE
Расход. Проблема в новой функции переноса таблицы данных чека в таблицу расходов

### ISSUE THREAD

**Issue by KonstantinSolo** [shcherbakov-vadim/1c-money-custom-issues#14]
Обновился на 2.0.44.28.41.
Загрузил чеки. 
1. открыл загруженный документ.
![image](https://github.com/user-attachments/assets/c1140e0d-7941-4d26-81d0-b55a772b4869)

2. Прописал соответствия
![image](https://github.com/user-attachments/assets/acba2270-103e-4fbf-aca2-a9783949b17c)
![image](https://github.com/user-attachments/assets/a5628656-ac86-4a7d-a08b-5af4556948c3)

3. Переключился на вкладку "Расходы". 
![image](https://github.com/user-attachments/assets/97bb4300-0240-4136-beb6-f1c34894182e)

4. Удалил строку "Загрузка чеков". 
![image](https://github.com/user-attachments/assets/e1a9c11e-dfe4-4c32-8b1c-86c718bd1df9)

5. На вкладке данных чека выделил все строки и нажал "Скопировать в расходы с группировкой" 
![image](https://github.com/user-attachments/assets/e73a2596-4584-4131-acf2-8de5c91ba3b8)

6. автоматом переключилось на вкладку "расходы", 1 строка заполнена "загрузкой чеков", остальные заполнены правильно.
![image](https://github.com/user-attachments/assets/9cbe0e57-9b91-4bd2-9cba-f6c94b35cfea)

7. удалил строки. Попробовал нажать "Заполнить по данным чека". одна строка  опять заменилась на "Загрузка чеков", остальные 2 перенеслись правильно.
![image](https://github.com/user-attachments/assets/b70f8422-d435-46af-b865-7958ce847cf5)

8. опять удалил строки, и на вкладке чека выделил строки и нажал "Скопировать в расходы". Все равно одна строка заполнена неверно.
![image](https://github.com/user-attachments/assets/4ee565fb-5edc-45ad-9254-be912bd5987d)

9. Сохранил документ (нажал на дискету и закрыл). Открыл заново. 2 строки на вкладке чека соответствие показали неверно.
![image](https://github.com/user-attachments/assets/1006e88c-4435-4246-ae6a-1638eb2ae2c0)

**Comment by KonstantinSolo** [comment]
Да, после того, как закончил тестировать, 
10. вручную заменил "загрузка чека" на вкладке расходов, прописал аналитики,
11. записал в "Сумма скидки" разницу (67р)
12. и нажал "Учесть".
В документ автоматом добавились строки
![image](https://github.com/user-attachments/assets/7b988fd8-f173-4986-8f92-4ca10ec3b7c6)

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.42
