### ISSUE TITLE
Расход. Проблема при переносе таблицы данных чека в таблицу "Расходы" кнопкой "Заполнить по данным чека"

### ISSUE THREAD

**Issue by KonstantinSolo** [shcherbakov-vadim/1c-money-custom-issues#15]
после обновления на кастом 2.0.44.28.41.
0. Документ уже не совсем нулевый (я по другой проблеме его уже заполнял и записывал), но на вкладке расходов строки я удалил, на вкладке данных чека соответствия прописал:
![image](https://github.com/user-attachments/assets/14570992-9a01-4a5b-8c47-0b5f85aa3e0b)

1. На вкладке "Расходы" нажимаю "Заполнить по данным чека". Одна строка заполняется расходом "Загрузка чеков". Остальные  заполняются нормально:
![image](https://github.com/user-attachments/assets/9ecd8415-07ad-4358-9148-8e85b4d79c5a)

2. поправил заполненную неверно строку (при этом включился флажок "Фикс"):
![image](https://github.com/user-attachments/assets/6bd305e7-e6fd-401b-84db-178da8437b93)

3. Нажал кнопку "Записать объект". Теперь неверно заполнилась другая строка
![image](https://github.com/user-attachments/assets/0fdaea08-c0fb-4e38-ba28-871f68802662)

4. поправил вторую строку
![image](https://github.com/user-attachments/assets/a9a8f575-0a09-4c87-833e-6596426b19f4)

5. после нажатия кнопки "Записать объект" получил ошибку:
![image](https://github.com/user-attachments/assets/60cf3388-40d4-4028-94db-d3c844f8e6db)

6. После нажатия на ОК получил сообщение об ошибке:
![image](https://github.com/user-attachments/assets/bde0ff4a-3d30-4516-8f01-cce230862c4c)

Не совсем понятно, откуда взялась сумма 4039,99, когда в таблице расходов сумма строк = 2040

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi#2.0.44.28.42
