### ISSUE TITLE
Расход. Автодобавление лишних строк при использовании скидки.

### ISSUE THREAD

**Issue by KonstantinSolo** [shcherbakov-vadim/1c-money-custom-issues#16]
Не понимаю, я неправильно что-то делаю, или это глюк?
0. Загружен чек. Соответствия прописаны. Сразу пишет о несовпадении суммы по колонкам с "Итоговой суммы чека".
![image](https://github.com/user-attachments/assets/1d6cabe0-7a83-4773-b02d-db2040e9a6f1)

1. Перенес данные в расходы кнопкой "Скопировать в расходы". 
![image](https://github.com/user-attachments/assets/9dad4d06-ff2a-44ef-a741-4a8f17367c54)
![image](https://github.com/user-attachments/assets/ff2418cd-7db8-4c1f-9fa8-b240a2cc3b08)

2. Заменил в первой строке статью расхода. Сумма не совпадает (это логично, т.к. я использовал при оплате бонусы).
![image](https://github.com/user-attachments/assets/c4505987-ef89-46ec-bd03-c9ff3ed0cbf1)

3. Указал сумму скидки в подвале. При этом ругательство пропало.
![image](https://github.com/user-attachments/assets/de5c01b2-e4af-4008-b2f1-fa3bd46db483)

4. Нажимаю  кнопку "Записать". В табл.часть расходов добавляются строки (видимо, чтобы сумма по строкам расходов была равна сумме по строкам таблицы чеков
![image](https://github.com/user-attachments/assets/8c917d87-a8ee-45c4-bbf3-a26a21971e87)

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi#2.0.44.28.42
