### ISSUE TITLE
Выбор УЗ почты для загрузки чеков

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#17]
Предлагаю реализовать возможность выбора из справочника, какую именно запись почты (из имеющихся настроенных в конфигурации) использовать для загрузки чеков.

**Comment by shcherbakov-vadim** [comment]
Загрузка чеков всегда выполняется под учетной записью, настроенной для конкретного пользователя. Поэтому выбирать не из чего

**Comment by gretis** [comment]
А если у пользователя настроено больше одной учетной записи почты?
Речь не про учетные записи пользователя программы, а про записи почты. Их у конкретного пользователя может быть больше, чем одна

**Comment by shcherbakov-vadim** [comment]
На данным момент предполагается, что в системе для каждого пользователя есть только одна учетная запись, в которой установлен признак "Для получения". Если для пользователя заполнено несколько учетных записей, включая общую учетную запись для получения (за исключением системной) - для получения чеков будет использоваться первая учетная, после сортировки по наименованию.
