### ISSUE TITLE
Добавить фильтры в отчет "Сравнение доходов и расходов за 2 периода"

### ISSUE THREAD

**Issue by KonstantinSolo** [shcherbakov-vadim/1c-money-custom-issues#18]
очень хочется иметь возможность фильтровать отчет по аналитике.
В других отчетах ("Динамика доходов и расходов", "Структура расходов", "Структура доходов") это есть.
Возможно, это уже можно как-то настройками поправить, но я не этого не увидел. Открыл настройки отчета, нашел на вкладке "Отбор" возможность фильтровать по разным реквизитам операции, например, по галке "Операция проверена", но и только. Возможности фильтрации по аналитике (в частности, мне надо фильтровать по аналитике "Пометка") - я не нашел.

![image](https://github.com/user-attachments/assets/c06c510b-6d56-4dd4-a0cf-9cd0850b7a95)

**Comment by KonstantinSolo** [comment]
в общем, пока вернулся к фильтру по автору документа (Операция.Пользователь) - это во всех нужных отчетах видел.. Не очень удобно, бывает надо отдельные строки в документе убрать, но по крайней мере уже работает...Даже в перемещениях, где аналитик вообще нет.

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.45
