### ISSUE TITLE
Ошибка в алгоритме работы с учетом предоплат

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#19]
Скорее нюанс. А как из него выходить - хотелось бы найти наиболее оптимальный выход. Порекомендуете?
Алгоритм работает только если УЖЕ есть сопоставление ИНН и контрагента. Если в ранее загруженных чеках данный контрагент еще не фигурировал (нет сопоставления), то запустить этот алгоритм необходимо как-то "извне".
Возможно, сделать доступным просмотр/редактирование связок "ИНН-контрагент"?

**Comment by shcherbakov-vadim** [comment]
Предполагается, что в настройках системы заполняется "кошелек или долг предоплаты" по умолчанию, на которого будут формироваться все новые документы мы дали в долг или перемещение. Затем если необходимо долги какого-то контакта выделить отдельно, в карточке контакта заполняется отдельный долг.
