### ISSUE TITLE
Ошибка при работе с опубликованной веб-версией

### ISSUE THREAD

**Issue by asazanoff** [shcherbakov-vadim/1c-money-custom-issues#2]
Доброго дня!

Использую для работы с конфигурацией (версия 2.0.44.28.35) публикацию базы через ibsrv. Все это крутится в контейнере на домашнем сервере.

При работе через тонкий клиент все замечательно работает. Но при работе через веб-версию при запуске возникает ошибка. Прикладываю отчет и подробный текст ошибки.

[report.json](https://github.com/user-attachments/files/16324015/report.json)
![screenShot](https://github.com/user-attachments/assets/9cbe67e8-6eb1-4026-8f38-06f1ed1a7fcf)

```
Ошибка инициализации модуля:
по причине:
{<Неизвестный модуль>(268,50)}: Тип не определен (ОписаниеОповещения)
	Параметры.Вставить("ОбработкаЗавершения", Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(274,51)}: Тип не определен (ОписаниеОповещения)
	Параметры.Вставить("ОбработкаПродолжения", Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(365,50)}: Тип не определен (ОписаниеОповещения)
	Параметры.Вставить("ОбработкаЗавершения", Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(369,51)}: Тип не определен (ОписаниеОповещения)
	Параметры.Вставить("ОбработкаПродолжения", Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(646,30)}: Тип не определен (ОписаниеОповещения)
	ОповещениеОЗакрытии = Новый <<?>>ОписаниеОповещения("ПоказатьПредупреждениеИПродолжитьЗавершение", ЭтотОбъект, Параметры);
{<Неизвестный модуль>(766,16)}: Тип не определен (ОписаниеОповещения)
	Возврат Новый <<?>>ОписаниеОповещения("ВыполнитьОповещениеСПустымРезультатом", ЭтотОбъект, ОповещениеСРезультатом);
{<Неизвестный модуль>(969,51)}: Тип не определен (ОписаниеОповещения)
	Параметры.Вставить("ОбработкаПродолжения", Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(1045,51)}: Тип не определен (ОписаниеОповещения)
	Параметры.Вставить("ОбработкаПродолжения", Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(1205,51)}: Тип не определен (ОписаниеОповещения)
	Параметры.Вставить("ОбработкаПродолжения", Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(1278,51)}: Тип не определен (ОписаниеОповещения)
	Параметры.Вставить("ОбработкаПродолжения", Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(1472,50)}: Тип не определен (ОписаниеОповещения)
	Параметры.Вставить("ОбработкаЗавершения", Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(1562,43)}: Тип не определен (ОписаниеОповещения)
	Параметры.ИнтерактивнаяОбработка = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(1588,30)}: Тип не определен (ОписаниеОповещения)
	ОповещениеОЗакрытии = Новый <<?>>ОписаниеОповещения("ПослеЗакрытияФормыНерекомендуемойВерсииПлатформы", ЭтотОбъект, Параметры);
{<Неизвестный модуль>(1665,43)}: Тип не определен (ОписаниеОповещения)
	Параметры.ИнтерактивнаяОбработка = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(1682,43)}: Тип не определен (ОписаниеОповещения)
	Параметры.ИнтерактивнаяОбработка = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(1703,9)}: Тип не определен (ОписаниеОповещения)
		Новый <<?>>ОписаниеОповещения("ПослеЗакрытияФормыВосстановленияСвязиСГлавнымУзлом", ЭтотОбъект, Параметры));
{<Неизвестный модуль>(1728,30)}: Тип не определен (ОписаниеОповещения)
		ОписаниеОповещения = Новый <<?>>ОписаниеОповещения("ПослеЗакрытияФормыВыбораНачальныхРегиональныхНастроекИБ", ЭтотОбъект, Параметры);
{<Неизвестный модуль>(1906,31)}: Тип не определен (ОписаниеОповещения)
	ОбработкаПродолжения = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(1941,31)}: Тип не определен (ОписаниеОповещения)
	ОбработкаПродолжения = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(2544,26)}: Тип не определен (ОписаниеОповещения)
	ОбработкаОтвета = Новый <<?>>ОписаниеОповещения("ПослеЗакрытияФормыПредупрежденийПриЗавершенииРаботы",
{<Неизвестный модуль>(2563,45)}: Тип не определен (ОписаниеОповещения)
			Параметры.ИнтерактивнаяОбработка = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(2576,44)}: Тип не определен (ОписаниеОповещения)
		Параметры.ИнтерактивнаяОбработка = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(2659,44)}: Тип не определен (ОписаниеОповещения)
		Параметры.ИнтерактивнаяОбработка = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(2677,44)}: Тип не определен (ОписаниеОповещения)
		Параметры.ИнтерактивнаяОбработка = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(2697,42)}: Тип не определен (ОписаниеОповещения)
		Параметры.ОбработкаПродолжения = Новый <<?>>ОписаниеОповещения(
{<Неизвестный модуль>(2712,33)}: Тип не определен (ОписаниеОповещения)
	ИнтерактивнаяОбработка = Новый <<?>>ОписаниеОповещения("ПоказатьПредупреждениеИПродолжить", ЭтотОбъект, ТекстПредупреждения);
```

<img width="877" alt="image" src="https://github.com/user-attachments/assets/4c335947-3ce5-48da-9c2e-1b8a0af3c6cd">

Подскажите, пожалуйста, это неготовность конфигурации для использования в браузере, или я что-то сделал не так?

Спасибо

**Comment by shcherbakov-vadim** [comment]
Напишите версию платформы и ОС. На версии 8.3.25.1286 в Windows 11 проблема не воспроизводится

**Comment by asazanoff** [comment]
Платформа 8.3.25.1257 в контейнере на основе ubuntu focal. Браузер edge на win11

**Comment by shcherbakov-vadim** [comment]
Платформа базовая? Если ПРОФ, используются ли расширения и внесены ли изменения в конфигурацию?

**Comment by asazanoff** [comment]
Платформа - без понятия. Прикладываю информацию из "О программе"
```
Текущая:
Searching for license on server:
Software license file not found
local key not available: Status=-100, ORGL8 Local, not set
local key not available: Status=-100, ORG8A Local, not set
local key not available: Status=-100, ORG8B Local, not set
nethasp.ini: is missing, default settings used, error connecting to license manager: Net Status=0, System Error=0, Warning=15, ORGL8 Network, not set
nethasp.ini: is missing, default settings used, error connecting to license manager: Net Status=0, System Error=0, Warning=15, ORG8A Network, not set
nethasp.ini: is missing, default settings used, error connecting to license manager: Net Status=0, System Error=0, Warning=15, ORG8B Network, not set
Информационная база:
Сетевой HASP4 ORGL8
5000000XXXXX, для разработчиков 1/4, 09.10.2023 19:45:28, 29.10.2023 11:18:23, 05.11.2023 11:18:23 (UTC)
80000YYYY, клиент 1/5, 25.03.2021 22:25:13, 16.12.2020 0:00:00, ООО Моя Компания
```

где:
`5000000XXXXX` Комьюнити лицензия, которая давно удалена и вообще не должна где-то использоваться
`80000YYYY` - рег номер УНФ на платформе Проф, который установлен на другом сервере и не должен пересекаться с Деньгами, о которой идет речь

Расширения не используются. Изменения в конфигурацию не вносились.

Сейчас в образ контейнера с автономным сервером установил 8.3.25.1374, ничего не изменилось, поведение осталось таким же.

В качестве эксперимента попробую запустить веб-сервер не в автономном сервере, а через публикацию через Apache, и проверить поведение в браузере, но это не в самое ближайшее время сделаю.

**Comment by shcherbakov-vadim** [comment]
Напишите команду, которой вы запускаете автономный сервер и если вы используете файл настроек yml приложите его содержимое

**Comment by asazanoff** [comment]
Команда `/opt/1cv8/x86_64/8.3.25.1374/ibsrv --data=/fs-data --address=any --port=80`
Директория с файловой БД прокидывается через 
```yaml
    volumes:
      - ./db-data:/fs-data/db-data
```
Файла с настройками не используется.

**Comment by shcherbakov-vadim** [comment]
Вы можете подготовить отдельный контейнер с демобазой и в случае воспроизведения проблемы выложить образ на файловом ресурсе?

**Comment by asazanoff** [comment]
Да, проблема воспроизводится с демобазой. И, видимо, это все же несовместимость Денег или моего образа с таким способом развертывания, поскольку это старая версия конфигурации 2.0.35.28 без ваших доработок.

 Тем не менее, прикладываю ссылку на каталог с БД, докерфайлом и compose, если интересно посмотреть https://1drv.ms/u/s!AiZXoZz3ouBKtYZMIJ1uUXd8uo57wA?e=T1N19t

**Comment by shcherbakov-vadim** [comment]
На Windows 11 в Docker Desktop все работает. Я использовал следующий конфиг:
services:
  1c-money-demo:
    container_name: 1c-money-demo
    image: asazanoff/1c-money:8.3.25.1374
    volumes:
      - ./db-data:/fs-data/db-data
    environment:
      TZ: Asia/Yekaterinburg
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.1c-money-demo.rule=Host(`money-demo.homesrv`)"
      - "traefik.http.routers.1c-money-demo.entrypoints=web"
      - "traefik.http.services.1c-money-demo.loadbalancer.server.port=80"
      - "traefik.http.routers.1c-money-demo.service=1c-money-demo"
    network_mode: bridge
    ports:
      - "9180:80"

**Comment by asazanoff** [comment]
Действительно, если делать expose порта и ходить по hostname:port, то ошибки не возникает. В моем случае доступ через traefik, и тут что-то идет не так. Возможно 1с не нравится домен, другой причины, почему возникают такие сложности, я придумать не могу. В любом случае спасибо за содействие!!!

**Comment by asazanoff** [comment]
Может кто еще случайно найдет и с таким же столкнется, вот здесь обсуждалось то же самое https://forum.infostart.ru/forum86/topic285376/
