### ISSUE TITLE
Расход. Не дает провести при несовпадении с суммой чека.

### ISSUE THREAD

**Issue by KonstantinSolo** [shcherbakov-vadim/1c-money-custom-issues#20]
Заказал лекарства в приложении аптеки. Указал в приложении, чтобы часть суммы (19р) оплатилась бонусами. Итоговая сумма - 1989. Судя по данным в ЛК банка - такая сумма и списалась.
Но чек пришел - на полную сумму, 2008:
 
![image](https://github.com/user-attachments/assets/184467af-f48f-4d95-af2c-f1d981502575)

Если я вручную пытаюсь указать сумму скидки на вкладке расходов, и потом провести документ - программа не дает (сейчас не видно на скрине, но в первый раз написала что-то о том, что сумма не совпадает с суммой чека):

![image](https://github.com/user-attachments/assets/0cb2b582-bf87-4548-aa85-9e030a69e3ab)

Прошу предусмотреть возможность проводить документ, даже если сумма не совпадает с суммой чека (ну или учитывать сумму скидки при проверке).

**Comment by shcherbakov-vadim** [comment]
В вашем случае 19 рублей это не скидка, а кэшбэк и он должен быть оформлен отдельной операцией

**Comment by KonstantinSolo** [comment]
Дело в том, что я не первый раз оплачиваю часть чека бонусами, в т.ч. в этой аптеке, и никогда такой ситуации не было, чтобы чек приходил на полную сумму (а сейчас даже в ЛК я заказ вижу на полную сумму, и никаких списаний бонусов). Такое ощущение, что у них там глюки (они недавно поменяли бонусную систему). 

> и он должен быть оформлен отдельной операцией

Ну я так и сделал, собственно. Но непонятно, почему так?

**Comment by shcherbakov-vadim** [comment]
Это вопрос к продавцу, а не к программе
