### ISSUE TITLE
Обработка числа в загружаемом файле

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#21]
На примере фрагмента файла, который формирует DzenMoney
Вышеупомянутое ПО выгружает CSV файл, заключая поля в кавычки - как текст. В том числе поля с суммами. Можно ли предусмотреть распознавание сумм в текстовых полях, если они в правиле загрузки выписки указаны как "Сумма прихода" или "Сумма расхода"? Иначе загрузка выписки не распознает их как числовые значения.
[dzenmoney.csv](https://github.com/user-attachments/files/18043036/dzenmoney.csv)
Если это нецелесообразно для реализации, подскажите, пожалуйста, как правильно написать правило в "Алгоритм перед чтением строки", чтобы числа все-таки распознавались как числа на этапе загрузки, а не методом предварительной правки файла

**Comment by gretis** [comment]
на данный момент решается указанием алгоритма перед чтением строки:
`
ПараметрыСтроки.Вставить("СуммаПоступления", ЧислоИзТекстаДоПервойБуквы(СтрЗаменить(ЗначенияСтроки["income"],"""","")));
ПараметрыСтроки.Вставить("СуммаСписания", ЧислоИзТекстаДоПервойБуквы(СтрЗаменить(ЗначенияСтроки["outcome"],"""","")));
`

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.45
