### ISSUE TITLE
Ошибка в обработке колонки "Ключ показателя"

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#24]
При загрузке выписки не распознаются части структуры, если в имени присутствует пробельный символ. Пример:

```
income = ЧислоИзТекстаДоПервойБуквы(СтрЗаменить(ЗначенияСтроки["income"],"""",""));
outcome = ЧислоИзТекстаДоПервойБуквы(СтрЗаменить(ЗначенияСтроки["outcome"],"""",""));
ПараметрыСтроки.Вставить("СуммаПоступления", income);
ПараметрыСтроки.Вставить("СуммаСписания", outcome);

Если outcome = 0 Тогда
	ПараметрыСтроки.Вставить("Комментарий", ЗначенияСтроки["payee"]);
	//ПараметрыСтроки.Вставить("Плательщик дохода", ЗначенияСтроки["payee"]);
ИначеЕсли income = 0 Тогда
	ПараметрыСтроки.Вставить("Комментарий", ЗначенияСтроки["payee"]);
	//ПараметрыСтроки.Вставить("Магазин, продавец", ЗначенияСтроки["payee"]);
КонецЕсли;
```

Если убираем комментарии, скрипт выдает ошибку.

> по причине:
> Задано неправильное имя атрибута структуры

**Comment by shcherbakov-vadim** [comment]
Предполагалось, что для предопределенных аналитик будут использоваться имена предопределенных элементов, которые можно посмотреть в списке "Аналитика статей" после вывода поля ИмяПредопределенныхДанных
![Screenshot_20241207_203804](https://github.com/user-attachments/assets/ed345a68-4907-42de-8d4e-d354dc223702)

Для добавленных аналитик для использования в алгоритмах в наименовании не должно быть пробела

**Comment by gretis** [comment]
Если это возможно, внесите уточняющую правку для потомков (и забывчивых) на [сайте](https://chtch.ru/ru/1sdengi/)
Там сейчас 
```
ПараметрыСтроки (Структура) - используется для записи и в него устанавливаются значения колонок, указанных в колонке "Ключ показателя"
```

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.45
