### ISSUE TITLE
Ошибка в работе алгоритма перед чтением строки при загрузке выписки

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#25]
Загружаю выписку.
Пытаюсь вычленить из общего списка строки перемещений. В этих строках сумма дохода больше нуля и сумма расхода больше нуля.
Поскольку алгоритм больше и используются в условиях эти же поля. сделал в начале переменные - возможно, проблема в них? Но я пытался отказаться от них, получил то же поведение.

Я попытался указать в условии просто проставить YEP/NOPE. Мне алгоритм указал ВСЕМ загружаемым строкам (не только перемещениям!) категорию "YEP".
Тогда я решил подставить туда сумму income. Это позволило увидеть, что всем строкам проставляется одинаковое значение, равное сумме ПОСЛЕДНЕГО имевшегося перевода.

```
income = ЧислоИзТекстаДоПервойБуквы(СтрЗаменить(ЗначенияСтроки["income"],"""",""));
outcome = ЧислоИзТекстаДоПервойБуквы(СтрЗаменить(ЗначенияСтроки["outcome"],"""",""));
comment = СтрЗаменить(ЗначенияСтроки["comment"],"""","");
payee = СтрЗаменить(ЗначенияСтроки["payee"],"""","");
outcomeAccountName = СтрЗаменить(ЗначенияСтроки["outcomeAccountName"],"""","");
incomeAccountName = СтрЗаменить(ЗначенияСтроки["incomeAccountName"],"""","");
categoryName = СтрЗаменить(ЗначенияСтроки["categoryName"],"""","");

ПараметрыСтроки.Вставить("Кошелек", outcomeAccountName);

Если income > 0 и outcome > 0 Тогда
//	ПараметрыСтроки.Вставить("СтатьяДолг", incomeAccountName);
//	ПараметрыСтроки.Вставить("СтатьяДолг", "YEP");
	ПараметрыСтроки.Вставить("СтатьяДолг", income);
Иначе
//	ПараметрыСтроки.Вставить("СтатьяДолг", categoryName);
	ПараметрыСтроки.Вставить("СтатьяДолг", "NOPE");
КонецЕсли;

// СТОРНО - работает
Если (СтрНайти(comment, "озврат ") или СтрНайти(comment, "ОЗВРАТ "))
		и income <> outcome Тогда
	ПараметрыСтроки.Вставить("СуммаПоступления", -outcome);
	ПараметрыСтроки.Вставить("СуммаСписания", -income);
Иначе
	ПараметрыСтроки.Вставить("СуммаПоступления", income);
	ПараметрыСтроки.Вставить("СуммаСписания", outcome);
КонецЕсли;
```

**Comment by shcherbakov-vadim** [comment]
Если нужно убрать из выписки перемещения, можно в алгоритме написать, что если сумма приход > 0 и сумма расход > 0 то обе суммы сбросить в значение 0

**Comment by gretis** [comment]
> убрать из выписки перемещения

их не нужно убирать. Просто когда загружается перемещение необходимо изменить счет (в котором указан "Долг") на значение из другого поля. А это сделать не получается. Как только я пытаюсь что-либо подставить в ПараметрыСтроки.Вставить("СтатьяДолг", ...) кроме фиксированного значения, начинается непредвиденное поведение, которое я попытался описать в тикете. Сбиваются значения кошельков по ВСЕМ строкам.

**Comment by shcherbakov-vadim** [comment]
Непредсказуемое поведение может быть, если вы указали для показателя "Начало таблицы операций" колонку, которая содержит пустые значения. Зачем вы заполняете в статью долг числовое значение - непонятно. Там должна быть либо строка, по которой будет выполняться поиск либо ссылка на элемент справочника

**Comment by gretis** [comment]
"Начало таблицы операций" - это колонка с датами и там всегда есть значения, пустые исключены.
Числовых значений в статью "долг" я и не пытался внести. Просто для строк, где в качестве "источника" или "приемника" указан "Долг", необходимо это самое слово "Долг" заменить на значение, взятое из другого столбца (payee). 
В случае с ZenMoney там немного сложнее получается, поскольку при загрузке в 1С нет возможности (пока по крайней мере) в качетсве источника указывать долг. Поэтому, всегда одностороннее направление и проще пойти руками завести операцию, а не грузить ее. Но это уже не совсем по теме текущего контекста :)

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.45
