### ISSUE TITLE
Переключение флажка "Операция проверена"

### ISSUE THREAD

**Issue by KonstantinSolo** [shcherbakov-vadim/1c-money-custom-issues#26]
Если в журнале выделить 1 или несколько документов и в меню по ПКМ выбрать пункт "Операция проверена", то, независимо от текущего статуса этого признака, в документе(-ах) он при этом будет включенным.
Т.е. если тебе надо выключить этот признак, надо каждый документ отдельно открывать и выключать этот флажок.

Просьба переделать реакцию на выбор пункта "Операция проверена" на переключение текущего статуса, или сказать, как можно это сделать на большом количестве документов.

**Comment by gretis** [comment]
инвертировать текущий статус - это непредсказуемое поведение. Тогда уж просто дать возможность выбрать: массово поставить либо массово снять

**Comment by KonstantinSolo** [comment]
> Тогда уж просто дать возможность выбрать: массово поставить либо массово снять

Как вариант. 
Ну т.е. я правильно понял, сейчас массово не выключить?

**Comment by shcherbakov-vadim** [comment]
Нужно делать отдельную кнопку "Вернуть на проверку"

**Comment by KonstantinSolo** [comment]
Если возможно, лично мне лучше команду в меню по ПКМ добавить.  Или там тоже будет?

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.45
