### ISSUE TITLE
Ошибка загрузки CSV, если дата заключена в кавычки

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#27]
Если поле даты в файле CSV заключено в кавычки, возникает ошибка.
Решением является алгоритм перед чтением строки
`ПараметрыСтроки.Вставить("Дата", СтрЗаменить(ЗначенияСтроки["date"],"""",""));`
Но, мне кажется, лучше это исправить в модуле

**Comment by gretis** [comment]
См также #21

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.45
