### ISSUE TITLE
Проблема с загрузкой аналитик в выписке

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#28]
Не знаю, как лучше описать словами, все видно на скриншотах
![image](https://github.com/user-attachments/assets/d2f0194e-a509-4771-87a6-6170ee24b300)
![image](https://github.com/user-attachments/assets/04d3c307-7ecd-4b42-b54b-fd30d32d77d3)
![image](https://github.com/user-attachments/assets/9033586b-1661-4424-a335-f5efb80d3af6)

**Comment by gretis** [comment]
альтернативно можно в явном виде указать в списке показателей. Тогда работает правильно. Но идея в том, чтоб указать данную аналитику только в тех операциях, в которых она "Истина"

**Comment by shcherbakov-vadim** [comment]
Насколько я понял, проблема в том, что если значение колонки пустое, оно не должно подбираться в первое правило, а только в правило по умолчанию, где пустое значение шаблона?

**Comment by gretis** [comment]
Если значение пустое - аналитика не должна добавляться. Если не пустое - добавляется аналитика со значением. Сейчас (подозреваю) пустое значение приравнивается к FALSE

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.45
