### ISSUE TITLE
Дополнить функционал скидок в расходах

### ISSUE THREAD

**Issue by Warelax** [shcherbakov-vadim/1c-money-custom-issues#3]
Сейчас ввод скидки в форме "Расход" разносит сумму скидки по позициям чека, пропорционально уменьшая сумму в поле "К оплате". Эта логика применима в сучае, когда в строках чека указана номинальная стоимость и скидка применяется к сумме чека.
Другим, гораздо более распространенным кейсом являются чеки, в строках которых указана стоимость со скидкой. В этом случае сумма чека уже включает скидку и ее сумма указывается лишь справочно.

С целью нормализации ввода расходов и учета актуальных цен предлагаю оснастить форму "Расход" флажком "Скидка включена в сумму" рядом с полем "Сумма скидки". Включение флажка изменит логику расчета, пропорционально увеличивая поле "Сумма", оставляя поле "К оплате" неизменным.

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.37
