### ISSUE TITLE
Загрузка данных чека из выписки - возможно?

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#31]
Настраиваю импорт из ДзенМани путем загрузки выписки. Одно из полей содержит данные о чеке в виде 
`t=20230712T0605&s=245.00&fn=9287440300849753&i=137032&fp=2041137896&n=1`
Можно ли, основываясь на этих данных, загрузить данные чека в 1С?

**Comment by shcherbakov-vadim** [comment]
Нет, в кастомизированную конфигурацию можно загрузить только результат выгрузки из мобильного приложения "Проверка чеков"
