### ISSUE TITLE
Отчет по проекту

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#33]
В стандартной "комплектации" есть аналитика "Проект". Но почему-то нет "инфраструктуры" для работы с этими проектами. В первую очередь, хотелось бы иметь возможность собирать отчет в разрезе проектов. Например, тут:
![image](https://github.com/user-attachments/assets/67ffe231-f288-4c25-a81a-ca2d699cfde1)

**Comment by gretis** [comment]
Возможно, в разрезе других аналитик тоже у кого-то будет интерес. Может быть, предусмотреть настраиваемый отчет по выбранной аналитике?

**Comment by shcherbakov-vadim** [comment]
В любом отчете, где доступно поле аналитика, можно выбрать конкретную аналитику в поля выбора или отбора. Если вопрос касается конкретного отчета, необходимо это указать

**Comment by gretis** [comment]
Ок, возможно, был неправ с хотелками и лучшее - враг хорошего :) Предлагаю пока закрыть
