### ISSUE TITLE
Если в выписке присутствует две одинаковые/похожие строки, вторая вызывает ошибку

### ISSUE THREAD

**Issue by gretis** [shcherbakov-vadim/1c-money-custom-issues#36]
В загружаемой выписке два перевода на одну и ту же сумму с одинаковыми источником, назначением. 
Приводит к созданию только одной операции. Попытка повторить и очистить ссылку на операцию показывает, что операция будет добавлена, но все равно не приводит к успеху

**Comment by gretis** [comment]
есть нюанс, возможно, важен - в столбце date дата без времени (так выгружает ZenMoney)

**Comment by shcherbakov-vadim** [comment]
Необходимо описать пример воспроизведения проблемы. Система поддерживает сопоставление нескольких операций с одинаковой датой и суммой

**Comment by gretis** [comment]
Точнее, чем в начале описать не смогу. Две одинаковые операции, описаны одинаковыми строками. Разница была только в столбцах, которые не участвуют в импорте - там указаны датавремя создания и датавремя последнего изменения, но ориентироваться на них как на дату операции будет некорректно. Возможно, конфликт возник из-за того, что столбец даты не содержит времени?

**Comment by shcherbakov-vadim** [comment]
Нет таких ограничений. Нужен пример файла и скриншоты

**Comment by gretis** [comment]
Файл уже удалил, но если повторится зафиксирую. Предлагаю тогда этот ТТ пока закрыть, при необходимости вернем
