### ISSUE TITLE
Учет кэшбека

### ISSUE THREAD

**Issue by Warelax** [shcherbakov-vadim/1c-money-custom-issues#4]
В документе расход добавить поле "Кошелек скидки", значение по умолчанию которого совпадает с полем "Расход из кошелька".
Если значения этих полей совпадают, или поле "Кошелек скидки" не заполнено, то расчет скидки остается как есть.

Если значение "Кошелек скидки" отличается от "Расход из кошелька", то:

- если флажок Включать в сумму не установлен, то формируется проводка "Сумма скидки" из "Расход из кошелька" на "Кошелек скидки". Скидка разносится по Статьям расхода уменьшая "К оплате" (как это сделано сейчас). Сумма из кошелька "Расход из кошелька" списывается на Статьи расходов с учетом скидки (поле "К оплате"), общая сумма списания с этого кошелька будет Статьи расходов + Сумма скидки.

- если флажок Включать в сумму установлен, то формируется проводка "Сумма скидки" из "Кошелек скидки" на "Расход из кошелька". Скидка разносится по Статьям расхода увеличивая "Сумма", оставляя "К оплате" неизменным. Сумма из кошелька "Расход из кошелька" списывается на Статьи расходов без учета скидки (поле "Сумма"), общая сумма списания с этого кошелька будет Статьи расходов - Сумма скидки.

**Comment by shcherbakov-vadim** [comment]
1. В общем случае бонусных счетов может быть несколько, например на ozon это баллы могут быть баллы продавца и баллы ozon. Для этого подойдет отдельная табличная часть на отдельной закладке
2. Не описано, как будут начисляться бонусы. Логичным выглядит опять же на закладке из п.1 делать возможность ввода начисленных бонусов по каждому бонусному счету
3. Можно сделать, что если бонусный счет один, то кошелек и сумма начисления указываются на закладке "Расходы", а если несколько то устанавливается отдельный флаг и на закладке "Расходы" указывается только итог, а детали на отдельной закладке

**Comment by Warelax** [comment]
Мне кажется на этом этапе лучше ограничиться одним бонусным счетом. Я согласен, что иногда случаются сложные операции, в которых задействуются более двух счетов. Но в нынешнем виде у нас есть один счет в шапке, табличная часть для статей бюджета, и одно поле для скидки, которому можно сопоставить один счет. Это закроет большинство задач без кардинальной переделки ввода.

А так конечно вместо четырех типов операций (расход, доход, перемещение, универсальная) можно было бы обойтись одной, где в табличной части можно было бы перечислять статьи бюджета и счета. Тем более, что статьи по сути те же счета. Такая форма двойной записи позволила бы единообразно учесть любые ситуации.

По пункту 2.
Бонусы начисляются на бонусный счет когда выполняются три условия:
- указана скидка
- флаг "включать в сумму" сброшен
- бонусный счет заполнен и отличается от "Расход из кошелька"

Другими словами, сейчас скидка как бы компенсирует "Расход из кошелька", но если значение "Кошелек скидки" иное, то скидка дебетует его.

**Comment by shcherbakov-vadim** [comment]
1. Если делать учёт бонусов, то нужно предусматривать разные варианты. Некоторые магазины на Озоне начисляются весьма приличные бонусы и наверняка найдутся пользователи, которые захотят их учитывать. В п.3 описано, как можно реализовать упрощённый вариант
2. Не понятно как вы планируете начислять бонусы. Логично делать это в документе расхода.

**Comment by Warelax** [comment]
1. Я в целом согласен. Но считаю, что еще одна табличная часть будет уже за рамками приемлемого для данной задачи. В программе уже есть Универсальная операция, такие кейсы можно проводить с ее помощью.
2. Так в предложенной мною схеме начисление бонусов происходит как раз в документе расхода. Баллы списываются когда флаг "Включать в сумму" установлен. А начисляются когда он сброшен.

**Comment by shcherbakov-vadim** [comment]
2. Поле "Включать в сумму" влияет на способ применения скидки и не должно влиять на кэшбэки. Пользователь может просто ввести сумму скидки, которая указана в чеке. Часть покупки пользователь хочет оплатить баллами и указывает бонусный счёт для этого. Должна ли эта сумма влиять на суммы скидки в строках большой вопрос. Можно сделать флаг. Далее по результатам покупки может быть начислен бонус. Для этого нужно отдельное поле. Насколько я понимаю вы хотите впихнуть все эти 3 поля (сумма скидки, списание бонуса, начисление бонуса) в одно. Это будет неудобно большинству пользователей.

**Comment by Warelax** [comment]
Да, вы правы, я хотел минимизировать усложнение интерфейса, но в результате видимо страдает юзабилити.
И действительно, мой вариант не позволяет обрабатывать ситуацию одновременного списания и начисления кэшбека, а это типовой случай. Ну не додумал, бывает, для этого и нужно обсуждение :)

Что касается расчета обычной скидки, которая указана в чеке, то я предложил прошлый тикет с прицелом именно на кэшбек. В коробочной версии Денег учет скидки на самом деле достаточен, поскольку позволяет верно учитывать расходы по статьям бюджета, а это и есть конечная цель всей затеи. Кстати, в таких монстрах как Quicken и MS Money реализован именно этот функционал и учет скидки ради учета скидки там не ведется.
Но нынешние программы лояльности разносят получение и реализацию скидок на разные даты и разные статьи бюджета, потому и возникла потребность в этих доработках.

**Comment by shcherbakov-vadim** [comment]
Если вам поле скидки нужно только для кэшбэка зачем его тогда вообще распределять по строкам? А если нужно распределять, то чем кэшбэк отличается от общей скидки по документу, которую можно воспринимать как кэшбэк который вам выдали в момент покупки и вы его сразу использовали?

**Comment by Warelax** [comment]
> Если вам поле скидки нужно только для кэшбэка зачем его тогда вообще распределять по строкам?

Так потому, что в строках у нас статьи бюджета. Суть не в учете оборота по кэшбеку (хотя это невредно), а чтобы правильно разнести затраты по статьям. Допустим по чеку нам начислили 30% кэшбека, с экономической т.з. это означает, что расходы по статьям этого чека следует на эти 30% уменьшить. Ну или отдельные статьи. А при списании кэшбека на покупки - наоборот, их следует увеличить пропорционально долевой стоимости кэшбека в оплате.

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.38
