### ISSUE TITLE
Смешанная операция в одном чеке

### ISSUE THREAD

**Issue by FedorovB** [shcherbakov-vadim/1c-money-custom-issues#5]
Вадим, добрый день.
Перешел на Вашу конфигурацию. Возник следующий вопрос.
У меня иногда в одном чеке есть мои расходы и расходы, которые меня просит осуществить другой человек. (например, когда я на работе иду в магазин и коллеги просят купить меня что-нибудь им).
Ранее я из расхода (загруженного с помощью мобильного приложения чека) все их позиции удалял, оставляя только свои, и на сумму удаленных позиций проводил операцию выдачи в долг. Оно и логично - это же их расходы - я им купил что-то, тем самым дав в долг, который они позднее мне возвращают, получая свои покупки (тут я уже оформляю операцию возврата долга).
А вот в Вашей конфигурации так сделать не получается. В расходе на вкладке "Данные чека" я вообще ничего изменить не могу по суммам, кол-ву (только наименование позиции могу изменить). А как только я удаляю эти позиции на вкладке "Расходы", то при сохранении и проведении документа они снова там восстанавливаются.
Как посоветуете быть в данном случае? Быть может у Вас как-то по другому реализован механизм учета данных операций?
Заранее Вам благодарен.

**Comment by shcherbakov-vadim** [comment]
Делаете статью расхода - "Затраты <имя коллеги>" и с помощью функциональности разделения и привязки данных чека отражаете такие расходы на эту статью. Затем когда человек с вами рассчитывается - делаете документ Расход с отрицательной суммой по статье "Затраты <имя коллеги>" и указанием кошелька, на который вернулись деньги. В отчете по доходам и расходам можно увидеть, какая сумма висит по таким статьям.

**Comment by FedorovB** [comment]
Спасибо. А нет ли у Вас в планах в дальнейшем модернизировать данные операции, чтобы проводить их не по статьям, а по долгам?

**Comment by FedorovB** [comment]
В принципе, мне пришла в голову еще одна идея - оставлять все, как есть в чеке (даже статью не менять), а потом делать операцию по данной позиции с отрицательным кол-вом, но в качестве кошелька выбирать долг контрагента, и потом уже делать операцию возврата...

**Comment by shcherbakov-vadim** [comment]
Таких планов нет, т.к. текущей функциональности достаточно, чтобы после окончания каждого месяца определяться, что делать с возникшей задолженностью. В случае если должник сразу отдаёт долг - оформлять отрицательный расход на кошелёк, если не отдаёт - оформлять отрицательный расход на долг

**Comment by FedorovB** [comment]
Вадим, кроме того, я сейчас обратил внимание на то, что при копировании операции расхода копируется и вкладка "Данные чека" в ней. А есть ли возможность скопировать данную операцию, но без этой вкладки (чтобы получилось, будто бы я создал операцию вручную, без загрузки чека)?

**Comment by shcherbakov-vadim** [comment]
Просьба по каждому вопросу или проблеме создавать отдельную Issue. Указанное вами поведение ошибочное и будет исправлено в следующей версии конфигурации.

**Comment by FedorovB** [comment]
Понял. Спасибо.
