### ISSUE TITLE
Загрузка курсов валют THB и AED.

### ISSUE THREAD

**Issue by FedorovB** [shcherbakov-vadim/1c-money-custom-issues#6]
Вадим, добрый день.
У меня в базе заведены валюты Дирхамов ОАЭ (AED) и тайских Батов (THB). Из настольного приложения загрузка курсов данных валют заканчивается с ошибкой:
![image](https://github.com/user-attachments/assets/7e9145f9-16c9-4359-b7c8-d7aed8bc5873)
Хотя, в мобильной версии приложения данные валюты загружаются без проблем.
Что самое интересное - в бухгалтерских базах у меня на работе таких проблем тоже не возникает.
Есть ли возможность поправить загрузку курсов данных валют?
Скриншот из журнала регистрации по данной ошибке прикрепляю. Заранее Вам благодарен.
![image](https://github.com/user-attachments/assets/7536a91a-9742-440d-81ce-2fdaf526f30a)

**Comment by shcherbakov-vadim** [comment]
В типовой конфигурации 1С:Деньги курсы валют загружаются с помощью сервиса cbrates.rbc.ru, который не выдает данные по данным валютам (об этом написано в журнале регистрации)
Нужно переделывать на сервис ЦБ https://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx
На работе у вас скорее всего настроена Интернет-поддержка ИТС и используется сервис от компании 1С

**Comment by shcherbakov-vadim** [comment]
Выяснилось, что проблема связана с устаревшим классификатором валют в 1С:Деньги, в котором для указанных валют не установлен признак возможности загрузки с сайта. 
Исправление включено в следующую версию конфигурации

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.39
