### ISSUE TITLE
Очистка полей аналитики при нажатии на кнопку "Заполнить по данным чека"

### ISSUE THREAD

**Issue by FedorovB** [shcherbakov-vadim/1c-money-custom-issues#7]
После сопоставлении статей расхода расходам на вкладке "Данные чека" я перехожу на вкладку "Расходы" и нажимаю кнопку "Заполнить по данным чека", чтобы проверить - все ли строчки корректно отображаются. Но после нажатия на данную кнопку все ранее установленные при редактировании данного документа аналитики очищаются и приходится их устанавливать повторно.
![image](https://github.com/user-attachments/assets/0cc9f5a9-022a-4389-ae89-eef2e24cd097)

**Comment by shcherbakov-vadim** [comment]
Исправление будет включено в следующую версию конфигурации

**Comment by shcherbakov-vadim** [comment]
1. Я прочитал ваше описание проблемы еще раз и понял, что ваш сценарий отличается от того, который мне удалось воспроизвести. С одной статьей в документе, проблемы вообще не должно возникать. Сделайте пожалуйста скриншот формы элемента аналитики "Бенефициар"
2. Какую версию кастомизированной конфигурации вы используете?

**Comment by FedorovB** [comment]
Добрый день. Данное поведение возникает преимущественно в том случае, если в чеке присутствуют ранее несопоставленные со статьями расходов строки.
Использую Вашу последнюю конфигурацию - 2.0.44.28.
![image](https://github.com/user-attachments/assets/09793a37-d091-414a-8e66-611a01cc0680)

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.39
