### ISSUE TITLE
Возможность выбора имущества при редактировании чека

### ISSUE THREAD

**Issue by FedorovB** [shcherbakov-vadim/1c-money-custom-issues#8]
Добрый день.
После загрузки чека невозможно выбрать имущества из соответствующего раздела "Имущество". Можно выбрать только статью расхода:
![image](https://github.com/user-attachments/assets/93c89693-e32a-4674-a9ff-04308be790f8)

При этом, выбрать имущество, как и было задумано еще в типовой конфигурации (когда идет покупка имущества) все еще остается:
![image](https://github.com/user-attachments/assets/74f6eba1-22cc-4d03-9b9d-58cbd7dd1313)

Это ошибка или так и задумано? Зараранее благодарен.

**Comment by shcherbakov-vadim** [comment]
Да, так задумано. Не предполагалось что может потребоваться определённое наименование чека постоянно относить на стоимость имущества

**Comment by FedorovB** [comment]
Понял. В таком случае, если я буду указывать на вкладке "Данные чека" статью расхода ("Операции с имуществом", например), а на вкладке "Расходы" уже само имущество, это ни что не будет влиять? В том плане - не будет ли со временем расход на вкладке "Расходы" заменен данными с вкладки "Данные чека"?

**Comment by shcherbakov-vadim** [comment]
Вы можете на закладке Данные чека вообще ничего не указывать. При ручном изменении данных на закладке Расходы автоматически ставится признак фиксации и эти данные ни при каких условиях не изменятся.
