### ISSUE TITLE
Ошибка при сопоставлении позиций из чека при работе через браузер

### ISSUE THREAD

**Issue by asazanoff** [shcherbakov-vadim/1c-money-custom-issues#9]
Здравствуйте!

Платформа 8.3.25.1374 , конфигурация 2.0.44.28.39. Публикация через автономный сервер на linux, но через апач на винде вроде также воспроизводится. При работе через тонкий клиент не воспроизводится.

1. Загружаю чеки с несопоставленными позициями
2. открываю чек, во вкладке "Данные чека" выбираю позицию номенклатуры через выпадающий список.
3. Появляется ошибка:
    ```
    Поле объекта не обнаружено (Фиксировать)
    {Документ.Расход.Форма.ФормаДокумента.Форма(2107)}:	Если НЕ Элемент.ТекущиеДанные.Фиксировать Тогда
    ```
4. Закрываю окно с ошибкой, продолжаю работать.

**Comment by shcherbakov-vadim** [comment]
Все-таки через Apache в Windows проблема воспроизводится или нет? Если нет, то мы возвращаемся к проблеме https://github.com/shcherbakov-vadim/1c-money-custom-issues/issues/2

**Comment by asazanoff** [comment]
<img width="960" alt="image" src="https://github.com/user-attachments/assets/7d4a8f55-0662-4e6a-8caf-a1638a1a7d43">
<img width="691" alt="image" src="https://github.com/user-attachments/assets/453065e1-fcfa-45cc-828d-7cbdaee6123e">
Воспроизводится.

Если редактировать статьи у уже сопоставленных позиций, ошибка не воспроизводится. Актуально только для позиций, с которыми не сопоставлена номенклатура.

**Comment by shcherbakov-vadim** [comment]
Вы уверены, что у вас установлена последняя версия кастомизированной конфигурации? Просто в последней версии в строке 1900 совсем другой код, а код на котором у вас ошибка находится в строке 2107.
Вы можете определить версию кастомизированной открыв в приложении регистр сведений "Версии подсистем" и посмотрев на поле Версия в строке с наименование МОД
Либо вы можете в конфигураторе открыть общий модуль МОД_ОбновлениеИнформационнойБазы и посмотреть на версию в функции ВерсияПодсистемы

**Comment by asazanoff** [comment]
Действительно, при проверке в апаче я взял не версию ближайшего обновления, а предыдущую. Показываю на текущей.

![image](https://github.com/user-attachments/assets/9825c61a-8b43-41d1-a6a3-10b09bee7ec2)
Версия МОД 1.0.0.39

**Comment by shcherbakov-vadim** [comment]
Удалось воспроизвести проблему, она связана с ошибкой платформы. Ее обход будет добавлен в следующей версии кастомизированной конфигурации. 
Пока вы можете установить режим "Выводить строки": Все

**Comment by shcherbakov-vadim** [comment]
https://chtch.ru/ru/1sdengi/#2.0.44.28.40
